# Generated by Django 5.0.6 on 2024-07-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
